### ISSUE TITLE
Fehler Backend index Page

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/bloecks#1]
Als zip von GH gezogen, installiert. Bei Klick auf den Blöcks Menüpunkt in der Hauptavigation bekomme ich Warning: include(): Filename cannot be empty in ... redaxo\src\addons\bloecks\pages\index.php on line 10

liegt daran das $subpage = rex_be_controller::getCurrentPagePart(2); https://github.com/FriendsOfREDAXO/bloecks/blob/master/pages/index.php#L6 NULL ergibt

**Comment by olien** [comment]
"Mehr" erreichst du schon wenn du die Plugins installierst.
Zumindest kannst du es dann (in der Struktur) nutzen.
Fehler kommen beim BlÖcks Menüpunkt immer noch...

**Comment by tbaddade** [comment]
Eventuell kann man das Addon so umbauen, dass es ohne Plugins oder zumindest initial gleich etwas mit installiert.

**Comment by tgoellner** [comment]
Ist in Version 0.2-alpha gefixt.
