### ISSUE TITLE
be.js.map fehlt

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/bloecks#105]
Redaxo 5.11.1 frisch aufgesetzt, dazu bloecks 3.0.0 mit aktiviertem cutncopy-Plugin...

Immer wenn ich die Artikelansicht lade, bekomme ich in der Console folgende Meldung:
DevTools failed to load SourceMap: Could not load content for ***/assets/addons/bloecks/plugins/cutncopy/js/be.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Hier im GitHub ist die Datei vorhanden und ich konnte sie so nachträglich hochladen um den Fehler zu beseitigen, aber im Installer scheint sie von Haus aus nicht mitgeleifert zu werden!?

**Comment by skerbis** [comment]
same as: https://github.com/FriendsOfREDAXO/bloecks/issues/96
