### ISSUE TITLE
Ausgabe-Problem

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/bloecks#109]
Hallo
Vorab: Super-Idee, sehr hilfreich, danke!

Das Problem:
Im Backend sieht alles gut aus - Bei der Ausgabe kommt nur dieses (Source der Seite im Browser):

...

echo '
&lt;div class="col-sm-12"&gt;
	'; // column wrapper
	&lt;div class="row rowblock"&gt;
		&lt;div class="col-sm-12"&gt;
			&lt;h1&gt;Hello!!&lt;/h1&gt;
		&lt;/div&gt;
	&lt;/div&gt;
	echo '
&lt;/div&gt;
'; // column wrapperecho '
&lt;div class="col-sm-6"&gt;
	'; // column wrapper
	&lt;div class="row rowblock"&gt;
		&lt;div class="col-sm-12"&gt;
			&lt;p&gt;
				Ich bin Blindtext. Von Geburt an. Es hat lange gedauert, bis ich begriffen habe, was es bedeutet, ein blinder Text zu sein: Man macht keinen Sinn. Man wirkt hier und da aus dem Zusammenhang gerissen. Oft wird man gar nicht erst gelesen. Aber bin ich deshalb ein schlechter Text? Ich weiss, dass ich nie die Chance haben werde, im Stern zu erscheinen. Aber bin ich darum weniger wichtig? Ich bin blind! Aber ich bin gerne Text. Und sollten Sie mich jetzt tatsächlich zu Ende lesen, dann habe ich etwas geschafft, was den meisten normalen Texten nicht gelingt.
				&lt;br&gt;
			&lt;/p&gt;
		&lt;/div&gt;
	&lt;/div&gt;
	echo '
&lt;/div&gt;
'; // column wrapperecho '
...

Danke für Hilfe/Klärung

**Comment by abra100pro** [comment]
Die obige Ausgabe kommt nur, wenn man das Add on "version" aktiviert hat.
In der Live-Ansicht erscheint das nicht.

**Comment by alxndr-w** [comment]
Hallo @abra100pro, ich würde gerne Hilfe leisten, aber ich verstehe ehrlich gesagt nicht, was du gemacht hast und auch nicht, was von da oben jetzt dein Problem darstellt und was so ist, wie du es eingegeben hast.

Kannst du evtl. hier den Moduleingabe-Code und den Ausgabe-Code reinkopieren, damit es etwas klarer wird?

Außerdem kannst du Code in 3 Backticks packen (statt 3x Punkte, wie du es gemacht hast, ``` oben und unten. Dann sieht er so aus und ist besser lesbar:

```
echo '
<div class="col-sm-12">
'; // column wrapper
<div class="row rowblock">
<div class="col-sm-12">
<h1>Hello!!</h1>
</div>
</div>
echo '
</div>
'; // column wrapperecho '
<div class="col-sm-6">
'; // column wrapper
<div class="row rowblock">
<div class="col-sm-12">
<p>
Ich bin Blindtext. Von Geburt an. Es hat lange gedauert, bis ich begriffen habe, was es bedeutet, ein blinder Text zu sein: Man macht keinen Sinn. Man wirkt hier und da aus dem Zusammenhang gerissen. Oft wird man gar nicht erst gelesen. Aber bin ich deshalb ein schlechter Text? Ich weiss, dass ich nie die Chance haben werde, im Stern zu erscheinen. Aber bin ich darum weniger wichtig? Ich bin blind! Aber ich bin gerne Text. Und sollten Sie mich jetzt tatsächlich zu Ende lesen, dann habe ich etwas geschafft, was den meisten normalen Texten nicht gelingt.
<br>
</p>
</div>
</div>
echo '
</div>
'; // column wrapperecho '
```

**Comment by abra100pro** [comment]
Hi @alxndr-w - Danke für dein Feedback. Ich habe ein kurzes Video dazu gemacht, welche issues ich mit slice_columns habe: https://www.dropbox.com/t/ntNd32eobXzCjgDz

Bin nicht sicher, ob ich hier in der richtigen Issues-Ecke gelandet bin, aber es war der Link in der Hilfe des add-ons...

**Comment by alxndr-w** [comment]
Das ist doch ein Feature von https://github.com/iceman-fx/gridblock nicht von https://github.com/FriendsOfREDAXO/bloecks/ oder?

**Comment by abra100pro** [comment]
Nein, es ist ein Feature von slice columns, bis gestern (???) zeigte der einzig sinnmachende Hilfelink im Add-on hierhin. Heute habe ich gesehen, dass ein eigener GitHub-Link drinsteht... Ich schreib's mal dort rein, macht hier keinen Sinn.
