### ISSUE TITLE
Nicht alle Blöcke lassen sich verschmälern

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/bloecks#110]
ein yform Formbuilder-Block wehrt sich "erfolgreich" gegen eine Verschmälerung.

**Comment by alxndr-w** [comment]
Kannst du einen Screenshot hier einfügen, damit klarer wird, was ein "Verschmälern" bei bloecks sein soll?

**Comment by abra100pro** [comment]
Verschmälern meint die Spaltenbreite verringern - ich habe ein kurzes Video dazu gemacht:
https://www.dropbox.com/t/ntNd32eobXzCjgDz

**Comment by skerbis** [comment]
Hier geht's weiter: https://github.com/FriendsOfREDAXO/slice_columns/issues/20
