### ISSUE TITLE
Wenn man einen eingefügten Block wieder löscht und einen Reload im Browser macht kommt ein whoops

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/bloecks#112]
AssertionError thrown with message "assert(isset($sliceId) && is_int($sliceId))"

Stacktrace:
#15 AssertionError in D:\weblocal\lus\src\addons\structure\plugins\content\pages\content.edit.php:6
#14 assert in D:\weblocal\lus\src\addons\structure\plugins\content\pages\content.edit.php:6
#13 require in D:\weblocal\lus\src\core\lib\packages\package.php:285
#12 rex_package:includeFile in D:\weblocal\lus\src\core\lib\be\controller.php:485
#11 rex_be_controller:{closure} in D:\weblocal\lus\src\core\lib\util\timer.php:57
#10 rex_timer:measure in D:\weblocal\lus\src\core\lib\be\controller.php:486
#9 rex_be_controller:includePath in D:\weblocal\lus\src\core\lib\be\controller.php:432
#8 rex_be_controller:includeCurrentPageSubPath in D:\weblocal\lus\src\addons\structure\plugins\content\pages\content.php:432
#7 require in D:\weblocal\lus\src\core\lib\packages\package.php:285
#6 rex_package:includeFile in D:\weblocal\lus\src\core\lib\be\controller.php:485
#5 rex_be_controller:{closure} in D:\weblocal\lus\src\core\lib\util\timer.php:57
#4 rex_timer:measure in D:\weblocal\lus\src\core\lib\be\controller.php:486
#3 rex_be_controller:includePath in D:\weblocal\lus\src\core\lib\be\controller.php:415
#2 rex_be_controller:includeCurrentPage in D:\weblocal\lus\src\core\backend.php:238
#1 require in D:\weblocal\lus\src\core\boot.php:143
#0 require in D:\weblocal\lus\public\redaxo\index.php:12

![Zwischenablage-1](https://user-images.githubusercontent.com/1277494/158873698-4b533fbe-30db-4339-ac80-cd8c4d1b3006.jpg)

**Comment by eaCe** [comment]
Das passiert mir auch mit einem normalen Slice. Das liegt im Core, nicht in bloecks, würde ich sagen..

**Comment by tyrant88** [comment]
Tatsache!

**Comment by Ricefarmier** [comment]
Hi ich habe das gleiche Problem und bei mir habe ich die Cores aktualisiert und es geht immer noch nicht gibt es noch eine andere Lösung
