### ISSUE TITLE
Kompatibilität "cutncopy" mit "search_it"

### ISSUE THREAD

**Issue by site-concept** [FriendsOfREDAXO/bloecks#12]
Fehler beim Ausschneiden eines Blocks bzw. wenn man den Block an einer anderen Stelle einfügt, gibt es einen Fehler: 
"ErrorException" thrown in redaxo/src/addons/search_it/lib/search_it.php on line 262
Fatal error: Object of class rex_article could not be converted to string

Wahrscheinlich versucht search_it die Änderung zu indizieren.

**Comment by alexplusde** [comment]
Was ist cutncopy? Ein Addon?

**Comment by site-concept** [comment]
Ein "Unter-Addon" von bloecks, um Blöcke zu kopieren oder auszuschneiden.

![grafik](https://cloud.githubusercontent.com/assets/13869688/22282813/f3fc0510-e2de-11e6-9ded-c9d62cda7ecd.png)
