### ISSUE TITLE
Per Drag n Drop verschobene Slice Blöcke werden nicht gespeichert

### ISSUE THREAD

**Issue by oioix** [FriendsOfREDAXO/bloecks#120]
**Per Drag n Drop verschobene Slice Blöcke werden nicht gespeichert**
Ich hab kürzlich das bloecks Addon von 3.1.1 auf 4.0.0 upgedatet.

Wie im Titel schon beschrieben, kann man zwar die Slice Blöcke nach wie vor per Drag n Drop verschieben, aber offenbar wird mit der neuen Version die neue Position (also der Prior) nicht mehr in der DB gespeichert. Zumindest nicht zuverlässig.
Im Browser Inspektor ist beim Verschieben auch keine xhr zu sehen.

Ich hab dann den assets-Ordner geprüft. Offenbar wurde da nicht sauber upgedated. Es waren noch die maps Dateien dort, die es im addon/assets-Verzeichnis nicht mehr gibt. Das plugin status war gar nicht da, wurde also nicht kopiert.
Siehe Bild (Status nach dem Update).

Ich habe daher alles aus dem addon/assets-Verzeichnissen (auch die plugin assets) manuell in den assets-Ordner kopiert. Hatte aber leider keinen positiven Effekt. Nach wie vor keine Speicherung in die DB und auch kein xhr zu sehen.

Habe daher wieder 3.1.1 installiert. Damit geht es wieder.

**Affected versions / Verwendete Versionen**
REDAXO: 5.16.1
AddOns: bloecks Version 4.0.0
Browser: aktueller Firefox 115.8.0esr auf Mac

![Screenshot 2024-03-02 | 18 38 43](https://github.com/FriendsOfREDAXO/bloecks/assets/75900789/6fb55526-d90e-4aa5-a418-79f9a2f7787e)

**Comment by skerbis** [comment]
ok da ist beim build etwas gelaufen was ich nicht nachvollziehen kann. Ich habe die Version zurückgezogen
