### ISSUE TITLE
CACHE :: "ParseError" wenn bloecks aktiviert

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/bloecks#14]
> "ParseError" thrown in /var/www/vhosts/domain.de/httpdocs/redaxo/cache/addons/structure/22.1.content on line 2
syntax error, unexpected '<'

in besagter Cache Datei steht dann: 

```
<?php if ($this->ctype == '1' || ($this->ctype == '-1')) { 
<li class="rex-slice rex-slice-draggable has--no-sortbuttons is--compact"><ul class="rex-slices is--undraggable">require rex_stream::factory('module/5/output', 
<<<'EOD_DB18CFC818F101E12EF8AF7331BE5B908ECFF1EC'
<header>
```

**Comment by skerbis** [comment]
Fehler tritt auf, wenn drag&drop aktiviert.

**Comment by tgoellner** [comment]
Das sollte eigentlich mit der Verison 1.3.6-alpha behoben sein - hast Du auch die aktuelle Version installiert?

**Comment by skerbis** [comment]
Problem ist eine Einstellung in Search_it. 
![bildschirmfoto 2017-02-03 um 13 38 34](https://cloud.githubusercontent.com/assets/791247/22592006/e97ae5da-ea17-11e6-98ca-110f750b43ff.png)
