### ISSUE TITLE
Status: Slice Status nicht standardmässig offline stellen

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bloecks#17]
Verwirrt extrem :-)

**Comment by tgoellner** [comment]
Beim Installieren wird das Feld slice_status auf 1 gesetzt - also ONLINE. Als Du es installiert hast, wurden all Deine Slices auf OFFLINE (slice_status = 0) gesetzt?

**Comment by olien** [comment]
Hey, Zumindest waren die Slices die ich neu angelegt habe per default auf "nicht sichtbar" gesetzt...

**Comment by skerbis** [comment]
sollte gelöst sein. - close
