### ISSUE TITLE
Slice Status vs. search_it-Crawler

### ISSUE THREAD

**Issue by Hirbod** [FriendsOfREDAXO/bloecks#24]
Ich hatte es zuerst bei cache_warmup gepostet, aber @staabm ist eher der Meinung, das bloecks sich darum kümmern sollte.

Deswegen auch hier noch mal: https://github.com/FriendsOfREDAXO/cache_warmup/issues/65

Kannst du dir das mal anschauen?

**Comment by alexplusde** [comment]
Ich grätsche mal rein: search_it crawlt auch alle Seiten - betrifft das evtl. auch dieses Addon?

/@tyrant88

**Comment by schuer** [comment]
Das Issue hat sich für Cache-Warmup übrigens erledigt, denn das wechselt vorm Generieren von Cachefiles in den Frontend-Modus, so dass auch der Slice-Status beachtet wird.

**Comment by tyrant88** [comment]
aktuell ruft search it die Artikel per Socket als Frontend-Seite auf. Also bin ich auch raus.
