### ISSUE TITLE
Neues Plugin: Autosave-Funktion speichert den aktuellen Stand bei der Eingabe

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/bloecks#25]
Feature-Idee, vermutlich als neues Plugin. Und vielleicht in Verbindung mit dem History Plugin als Vorbedingung: Ein Autosave-Feature für Blöcke. Superärgerlich, wenn man sich einen tollen Text aus den Fingern gesaugt hat, und dann nicht WP-like die Inhalte des aktuellen Blocks gespeichert werden..

**Comment by tbaddade** [comment]
> WP-like die Inhalte des aktuellen Blocks gespeichert werden

Was heißt das "WP-like" genau? Was macht Wordpress anders?

**Comment by skerbis** [comment]
Das könnte sich als schwierig erweisen. Bei WP gibt es meist nur eine Textarea, die zwischengespeichert werden muss. Ein Modul kann dagegen X Felder haben.

**Comment by staabm** [comment]
Man könnte es client seitig via js speichern bis es am server erfolgreich angenommen wurde (z.b. Via localstorage o.ä.)

**Comment by cukabeka** [comment]
bei WP ist es nicht schlimm, wenn der browser abstürzt, das handy ausgeht etc - es gibt immer eine zwischengespeicherte Version des angefangenen Artikels. Ich hatte leider schon ein paar Mal das Problem, dass ich ein komplexes Textile-Konstrukt im Editor hatte und dann der Browser starb o.ä. - bei WP gab es zumindest eine etwas frühere Version.
Localstorage könnte gehen, das kenne ich nicht und kann ich nicht beurteilen - allerdings wäre auch für die viel diskutierte Blog-Funktion innerhalb der REX-Api eine Art temporär-Version eines Artikels notwendig. Oder ein Aufbau auf dem History Plugin. Dort ist es ja auch möglich, mehrere Felder zu versionieren. EIn Autosave ist ja nichts anderes als ein Versionieren mit einem Flag "noch nicht approved", oder?

**Comment by skerbis** [comment]
Core Thema?

**Comment by alexplusde** [comment]
Müsste man das nicht an die history hängen?

**Comment by alexplusde** [comment]
Dazu braucht es einen zusätzlichen Zustand und ich fände es auch gut, dass nicht jede Zwischenversion am Ende erhalten bleibt. Bei einer Veröffentlichung sollten Entwürfe des Slice wieder verworfen werden, sonst hat man nur Karteileichen in der DB.

Was ist mit Daten, die validiert werden? Oder wenn die Verbindung unterbrochen wird? Müsste dann auch eine Fehlermeldung ausgegeben werden?

Man könnte die Funktion in Blöcks ausreifen lassen und dann in den Core überführen...

**Comment by schuer** [comment]
Was Alex sagt. Könnte man im Core umsetzen, aber auch als blÖcks-Plugin züchten.
