### ISSUE TITLE
Block hinzufügen unscharf

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/bloecks#26]
![image](https://cloud.githubusercontent.com/assets/3855487/25172900/ae9445b8-24f2-11e7-8066-618826f184fe.png)

Grund dafür ist `translateY(-75%)`, das das Element auf einem halben Pixel positioniert. Bei Retina vielleicht kein Problem - in der allgemeinen Anwendung jedoch schon.

**Comment by skerbis** [comment]
Ist wohl behoben @alexplusde - oder?
<img width="854" alt="bildschirmfoto 2017-09-20 um 23 29 46" src="https://user-images.githubusercontent.com/791247/30668638-ade23c64-9e5b-11e7-85d2-c3ec83d48320.png">

**Comment by alexplusde** [comment]
stimmt.
