### ISSUE TITLE
Status beißt sich mit History

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/bloecks#31]
<img width="1451" alt="28337713-d6ab06bc-6c06-11e7-9469-9d67183f9a7e" src="https://user-images.githubusercontent.com/791247/29204713-e7c71cd6-7e78-11e7-9f99-ea1ee9c672fe.png">

https://github.com/redaxo/redaxo/issues/1171#issuecomment-316182440
Einige Slices werden in der Gegenüberstellung nicht dargestellt. Die Wiederherstellung ist jedoch korrekt.

**Comment by schuer** [comment]
Kannst du mit der neuen Version 1.4.0 nochmal testen, @skerbis. Ich konnte deinen beschriebenen Fehler leider nicht nachvollziehen.

**Comment by skerbis** [comment]
Ja scheint sich erledigt zu haben. Danke ❤️
