### ISSUE TITLE
Error bei drag n' drop // copy/paste geht nicht

### ISSUE THREAD

**Issue by abra100pro** [FriendsOfREDAXO/bloecks#32]
1. Wenn ich einen Block via d&d verschiebe, dann aktiviert sich der safe mode. Siehe Bild.
2. Copy/Cut und Paste geht nicht - beim Klick auf den entspr. Button passiert nichts, der Block erscheint dann auch nicht in "Block hinzufügen".

Auf verschiedenen Installationen unter Linux und MAMP dasselbe. Immer mit Redaxo 5.3.0 - alles up to date.

![screen shot 2017-07-23 at 10 39 00](https://user-images.githubusercontent.com/7532646/28497954-f19b4488-6f93-11e7-89f2-e98c02d22bc2.png)

**Comment by skerbis** [comment]
sollte behoben sein
