### ISSUE TITLE
SQL Fehler : Status kann nicht installiert werden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#33]
Die Tabelle `rex_article_slices` wurde aus einer Redaxo 4 Instanz konvertiert, wo bereits die Spalte `status` und das dazugehörige AddOn `Slice Status` installiert war.

```
PlugIn status konnte aus folgendem Grund nicht installiert werden:
SQL error: Error while executing statement "ALTER TABLE `rex_article_slice` CHANGE `status` `status` tinyint(1) DEFAULT '1' NOT NULL unsigned;"! SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'unsigned' at line 2
```

**Comment by tbaddade** [comment]
Sehe grad, dass der Fehler bereits korrigiert wurde.
https://github.com/FriendsOfREDAXO/bloecks/pull/28

Ein neues Release wäre daher fein.

**Comment by alexplusde** [comment]
Es gibt blöcks gerade nicht mal mehr im Installer...

**Comment by schuer** [comment]
Der Installer scheint aber auch kaputt zu sein. Im Slack liest man immer wieder davon, dass Leute ihre Releases nicht veröffentlicht bekommen. Ich habe gerade auch das Problem :-/

**Comment by tbaddade** [comment]
ping @gharlan

**Comment by gharlan** [comment]
ping @tbaddade Liegt am URL Cache-Problem. Deswegen wird auf redaxo.org zurzeit der URL-Cache per Cronjob neu generiert. Daher fehlt direkt nach dem Releasen oft noch die URL, und daher klappt der Download dann nicht. Wenn man es nicht weiß, frustrierend. ;)
Aktuelle Lösung: Nach Release 5 Minuten warten, und dann testen.

Oder ist es bei dir noch ein anderes Problem @schuer ?

**Comment by schuer** [comment]
Ah, gut zu wissen, @gharlan. Bei mir ist es allerdings ein anderes Problem, ich kriege beim Veröffentlichen des Basisdemo-Releases folgende Meldung:

> Der Webservice liefert folgende Fehlermeldung: Die Package-Version fehlt!

**Comment by gharlan** [comment]
Hmm das ist sehr merkwürdig, kann mich nicht dran erinnern, dass die Meldung schon mal jemand gemeldet hatte. Oder kam die in letzter Zeit in Slack vor?

Also so generell funktioniert der Upload, gerade getestet.

Was machst du genau? Neue Version zu dem Addon erstellen?
Die "Zip-Datei erstellen und hochladen"-Checkbox ist angehakt und disabled?
Ganz oben steht die korrekte Versionsnummer?

**Comment by schuer** [comment]
@gharlan Im Slack kamen verschiedene Meldungen vor, meine ich. Ich kann mich allerdings nicht erinnern, dass meine schonmal genannt wurde.

Vorgehen genau so, wie du es beschrieben hast: AddOn passend vorbereitet mit Versionsnummer in package und so, danach im Installer neue Version, Nummer stimmt, Checkbox ist angehakt und disabled. Beim Abschicken läuft es 10-20 Sek, bevor die Fehlermeldung kommt.
Das Package ist um die 10 MB groß, vielleicht ist das nach den letzten Server-/Website-Anpassungen ein Problem?

**Comment by tgoellner** [comment]
Hatte das gleiche Problem am Dienstag - und heute immernoch. Habe Redaxo 5.3.0, läuft auf PHP 7.0.19. Installer ist auch aktualisiert und läuft auf Version 2.1.2.

Ich gehe den Installer, klicke auf "Eigene hochladen", dann bei BLOECKS auf ANSEHEN, lege über das kleine PLUS-Icon links oben eine neue Version an - dort steht dann auch die aktuelle Version 1.3.11. Gebe dann noch ein paar Angaben zur Version ein, ONLINE ist angehakt, ebenso ZIP ERSTELLEN UND HOCHLADEN (ist auch ausgegraut). Dann rödelt er ca. 10s und meldet dann "Der Webservice liefert folgende Fehlermeldung: Die Package-Version fehlt!".

**Comment by tgoellner** [comment]
...aha, guter Tipp @schuer - ich hab kurz die node_modules rausgeschmissen und schon klappte es! Müsste nun online sein.

**Comment by tbaddade** [comment]
> Das Package ist um die 10 MB groß, vielleicht ist das nach den letzten Server-/Website-Anpassungen ein Problem?

Ich meine, das Problem hatte @polarpixel auch schon mal.

**Comment by gharlan** [comment]
`upload_max_filesize` stand tatsächlich auf 8M.
@schuer Probiere jetzt bitte nochmal.

**Comment by schuer** [comment]
@gharlan Leider noch das gleiche Problem.

**Comment by tgoellner** [comment]
Sollte man vielleicht eine Art `.installerignore`-Datei andenken, damit der Installer beim Addon-Upload nicht alles (node_modules bspw.) ins ZIP schiebt?

**Comment by schuer** [comment]
Jetzt ist es online, @gharlan. Was immer du gerade noch justiert hast, danke :)

**Comment by gharlan** [comment]
@tgoellner Sollte man. Gerne als Issue. ;)

**Comment by alexplusde** [comment]
Danke!
