### ISSUE TITLE
Einstellungsseiten überarbeiten (Settings, READMEs, Screenshots)

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/bloecks#35]
Nimmt nur Platz weg im Menü und kann nichts.

**Comment by skerbis** [comment]
Ah doch?
<img width="774" alt="bildschirmfoto 2017-09-20 um 23 28 01" src="https://user-images.githubusercontent.com/791247/30668545-68f82398-9e5b-11e7-8698-017fbcc32f39.png">

**Comment by alexplusde** [comment]
Dass Redaxo da 100 einzelne Menüpunkte hat, macht es echt nicht übersichtlich. Könnte man das nicht als Unterseite ins System in die Nähe von be_style verfrachten? Ein Menüpunkt für eine Checkbox. 

Die restlichen Sichtbarkeits-Einstellungen bei blöcks (bspw. ausschneiden, kopieren, unsichtbar-schalten, etc.) sind nur über Rollen zuweisbar, da wäre es konsistent, diese Eigenschaft auch in eine Rolle zu packen.

**Comment by skerbis** [comment]
Diesen Menüpunkt sehen nur Admins. Sicher kann man es auch unter /system ablegen, aber es ist aktuell nicht üblich, so dass die Einstellung evtl. nicht gefunden wird.

**Comment by tbaddade** [comment]
https://github.com/redaxo/redaxo/issues/151

**Comment by alexplusde** [comment]
![image](https://user-images.githubusercontent.com/3855487/44526615-e3d5e400-a6e4-11e8-8ed8-4aeb8875d5fe.png)

Das Plugin könnte die Einstellungsseite erzeugen, so ergibt es wenig Sinn.

**Comment by schuer** [comment]
Ich würde das Konzept beibehalten, dass jedes blöcks-Plugin eine Einstellungsseite mitbringen kann, die sich wie bisher als Tab einhängt. (Aktuell ist das nur eine Seite, so dass es nicht deutlich wird.)

Ich würde es dahingehend anpassen, dass — wie bei anderen AddOns inzwischen üblich — jeweils die READMEs ausgegeben werden, so dass in jedem Fall ein Tab pro PlugIn erscheint, sowie zusätzlich ganz links der Tab für das BlÖcks-AddOn selbst:

| blÖcks | Cut & Copy | Drag & Drop | Status |

Der Inhalt eines jeden Tabs wäre dann Settings — sofern vorhanden — gefolgt von README.

In Ordnung für euch?

**Comment by alexplusde** [comment]
Wäre okay. Ändert am Grundproblem der vielen Menüpunkte nichts, aber zumindest werden die Seiten dann aufgewertet.

**Comment by schuer** [comment]
Ist inzwischen im Master-Branch enthalten und wird in Kürze releast. Ich hatte leider verpasst, an geeigneter Stelle in den Commits zu referenzieren.
