### ISSUE TITLE
Block ausschneiden und auf anderer Seite einfügen

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/bloecks#39]
Wenn man "Block ausschneiden" nutzt gibt es einen Fehler im Frontend, der anscheinend mit dem Cache von Redaxo zusammen hängt.
Der Fehler tritt auf, wenn man einen Block von einer "alten" Inhalsseite auf eine andere "neue" Inhaltsseite verschieben möchte. 

Im Backend ist alles korrekt.
Auf der alten Seite ist der Block weg und auf der neuen Seite ist der Block drinnen und im Frontend auch zu sehen.
Im Frontend auf der alten Webseite sieht man allerding den alten / ausgeschnitten Block immer noch, selbst wenn man den Browser-Cache löscht.
Erst wenn ich unter System "Cache löschen" klicke oder auf der alten Seite nochmal etwas anderes ändere, stimmt das Frontend auf der alten Seite wieder.

Anscheindend kriegt der Redaxo-Artikel-Cache von dem "Block ausschneiden" nichts mit.

Redaxo Version: 5.3.0
Blöcks Version: 1.3.11

**Comment by skerbis** [comment]
@brandes-webdesign besteht das Problem noch?

**Comment by schuer** [comment]
Ich habe das beschriebene Verhalten getestet und kann keine Probleme feststellen. @brandes-webdesign, hast du evtl. den SEO-Inspector im Einsatz? Dort gibt es aktuell ein Problem mit blÖcks, das genau zu deinem beschriebenen Fehlerverhalten passt: FriendsOfREDAXO/seoinspector#4

Ich schließe hier, und sollte SEO-Inspector nicht im Spiel sein und dein Problem weiterhin existieren, öffne bitte das Issue erneut.
