### ISSUE TITLE
Möglichkeit, Spalten unterschiedlich breit zu machen

### ISSUE THREAD

**Issue by patrickhoehn** [FriendsOfREDAXO/bloecks#4]
Es wäre schön, wenn man die Spalten unterschiedlich breit machen könnte. Z.B. in einem 12er Raster nicht nur 6-6, 4-4-4 etc., sondern z.B. auch 4-8, 6-3-3 etc.

**Comment by tgoellner** [comment]
Bezieht sich auf die alte Version (< 1.1-alpha), das Columns-Plugin muss nochmal komplett überarbeitet werden.

**Comment by skerbis** [comment]
Das PlugIn gibt es nicht mehr - daher close
