### ISSUE TITLE
node_modules im Installer

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/bloecks#41]
Das Verzeichnis `node_modules` ist im Installer gelandet, sollte da besser wieder raus :)

**Comment by marcohanke** [comment]
Darf ich das hier noch mal pushen? ich schiebe gerade 48,2MB node_modules auf den Server

**Comment by marcohanke** [comment]
Wollte gerade ein PR machen, aber hier ist node_modules ja schon raus. ist die Version im Installer auch schon ohne? Dann kann das hier geschlossen werden ...

**Comment by schuer** [comment]
@marcohanke Die node-Modules sind nicht mit im Repo, aber sie landen leider mit im Installer, wenn man nicht aufpasst. Insofern ist es hier mit einem PR nicht getan, sondern es muss ein neues Release für den Installer gebaut werden.

**Comment by marcohanke** [comment]
Ahh, OK,
ich dachte ich könnte auch mal helfen, … wieder nix ;-)

**Comment by schuer** [comment]
Gefixt in #44

**Comment by alexplusde** [comment]
ist ein release schon erfolgt? Hier sind wieder node_modules en masse drin.

**Comment by marcohanke** [comment]
War gefixt, neues Update, neues Problem

**Comment by schuer** [comment]
Neues Release 1.3.14 ist raus ohne node_modules. Hoffentlich.
