### ISSUE TITLE
Fehlendes visuelles Feedback bei ausgeblendeten Blöcken

### ISSUE THREAD

**Issue by alexwenz** [FriendsOfREDAXO/bloecks#42]
Blöcke werden nicht ausgegraut dargestellt, solange dem Nutzer über die Rolle nicht explizit das Recht "blÖcks Einstellungen" zugewiesen wurde. 

Dies sollte m.E. eigentlich unabhängig von dieser Einstellung funktionieren.

(blÖcks 1.3.12, REDAXO 5.4.0, getestet in Firefox und Chrome)

**Comment by mbodon** [comment]
jaja - kann mich nur anschließen, aber vermutlich bringt es ja nichts da nicht weiterentwickelt wird ... schade ...

**Comment by cukabeka** [comment]
![image](https://user-images.githubusercontent.com/688274/57771463-10b6a500-7713-11e9-914c-13d7ae74df1a.png)

Kann ich ebenfalls bestätigen. Vermute auch, dass das mit den Rechten und dem fehlenden CSS/JS zusammenhängt
