### ISSUE TITLE
bloecks/status greift nicht im Frontend

### ISSUE THREAD

**Issue by muenzberg-me** [FriendsOfREDAXO/bloecks#43]
**Fehlerablauf 1:**
Ich schalte ganz normal über das Auge den Block offline und er graut sich aus.
Sobald ich aber dann ins Frontend schaue ist dieser immer noch online.
Erst wenn ich den Cache lösche greift der Status und er verschwindet im Frontend.

**Fehlerablauf 2**
Ich habe einen Artikel mit Offline-Blöcke und editiere iregendeinen anderen Slice.
Sobald ich dann in das Frontend wechsel sind alle Blöcke die erst offline waren wieder sichtbar.
Beim überprüfen im Backend ist alles unverändert grau und ich muss wieder den Cache löschen.

**Comment by screenfox** [comment]
Wenn das Addon seoinspector installiert ist, dann dieses mal deaktiveren und erneut testen.

**Comment by skerbis** [comment]
@muenzberg-me hat sich das issue erledigt?

**Comment by omphteliba** [comment]
Hatte das gleiche Problem und das Deaktivieren des seoinspectors hat geholfen!

Danke!

**Comment by cukabeka** [comment]
Ah interessant, hatte das issue auch mit seoinspector. cache löschen hat geholfen, jetzt werden slices mit offline status nicht mehr angezeigt

**Comment by alexplusde** [comment]
Ist das wirklich eine Lösung @schuer

**Comment by schuer** [comment]
@alexplusde Das Problem scheint am Seoinspector zu liegen, der Artikelinhalte generiert, um deren Metadaten auszulesen. Es gibt ein Issue dort. Sollte sich zeigen, dass es doch an blÖcks liegt, wird man dort schließen und hier erneut öffnen.
