### ISSUE TITLE
Bloecks Addon erzeugt riesen Datei- / Datenmenge (7.765 Dateien | ca. 45 MB)

### ISSUE THREAD

**Issue by brandes-webdesign** [FriendsOfREDAXO/bloecks#44]
Moin zusammen,
ich hab eben alle Dateien von einer Webseite vom Demo-Server 1 zu 1 auf den Live-Server kopiert.

Dabei ist mir aufgefallen, dass das Addon "Bloecks" 7.765 Dateien mit knappen 45 MB umfasst.
Ich finde das reichtlich viel.

Ist da ein Fehler bekannt ???
Oder wie kommt diese riesen Datenmenge zusammen ?

Redaxo Version 5.4
Bloecks Version 1.3.12

Ich hab das Addon per Installer installiert.
Ggf. mit ein paar Updates nachträglich, weil das Projekt schon etwas länger geht.

Hinweis von Daniel Weitenauer:
"Die Zip enthält die komplette Entwicklungumgebung mit allen node_modules. Ich glaube, die gehören da nicht rein."

Vielen DANK für Eure Hilfe
Mirco

**Comment by skerbis** [comment]
Ich habe das Release aktualisiert im Installer. Um das Problem zu beheben: Addon deinstallieren, löschen, neu aus dem Installer ziehen.

**Comment by schuer** [comment]
Duplikat #41

**Comment by alexplusde** [comment]
Wurde in #41 behoben
