### ISSUE TITLE
Status eines Blocks wird nicht beim ausschneiden/kopieren nicht übernommen

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/bloecks#45]
Offline-Block ist nach dem Ausschneiden und Einfügen online.

**Comment by skerbis** [comment]
ist doch ok - warum sollte ich es sonst kopieren wollen?

**Comment by alexplusde** [comment]
Ich kann bspw einen Block als Vorlage nehmen und erst anschließend bearbeiten und veröffentlichen wollen.
