### ISSUE TITLE
Der CSRF-Token ist nicht gültig.

### ISSUE THREAD

**Issue by VIEWSION** [FriendsOfREDAXO/bloecks#46]
Ich bekomme bei Drag&Drop jetzt ständig diese Meldung... hat das was mit dem letzten Redaxo Update zu tun?

**Comment by elpschulzo** [comment]
Ja, das ist bei mir auch so. D'n'D Verschieben ist aktuell nicht nutzbar.

**Comment by Hirbod** [comment]
über nen Monat, bei einem der wichtigsten Addons. Ich bin leider überhaupt nicht im Thema, ich hab nur mitbekommen das es jetzt Core-Funktionen gibt und ich nehme an, diese müssen beim Ajax-Request beachtet und der Token mitgeschickt werden. @tgoellner kannst du dich dem annehmen?

**Comment by staabm** [comment]
für die leute die dieses addon als "wichtigstes addon" in ihrem setup nutzen wird sich ja dann vermutlich jemand finden der dieses problem lösen wird.

wenn man diese aussagen hier so ließt möchte man fast hoffen dass man niemals selbst ein addon verwalten muss welches für andere "das wichtigste addon" ist.

**Comment by Hirbod** [comment]
Wichtig in dem Sinne, da ich weiss, wie viele Leute dieses AddOn als defacto Standard in ihren Installationen nutzen. Da ich das AddOn auf 15 Installationen habe und es seit dem Update auf 5.5 nicht mehr läuft (ohne auf die extreme BC hinzuweisen) und ich in 15 Setups "Drag & Drop" deaktivieren musste. Und wie du vielleicht mitbekommen hast aus Slack, hab ich mich bereits beim Georg informiert, wie das Problem behoben werden könnte, damit ich einen PR schicke.

**Comment by alexplusde** [comment]
Es geht vlt. auch weniger darum, wie wichtig jetzt einzelne Addons sind, als darum, dass der CSRF-Schutz in der Praxis BC-breaking war und mehr Vorlauf bei den Addon-Entwicklern benötigt hätte.
