### ISSUE TITLE
Kopieren und Ausschneiden ohne Funktion, wenn structure/version aktiv ist

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/bloecks#47]
Hi,
ich habe gerade das aktuelle Blöcks 1.3.12 im aktuellen Rex5.5.1 am Laufen, kann aber weder die Kopieren noch die Ausschneidern-Funktionen benutzen.

Die Schaltflächen ändern Ihre Farbe nicht und auch die zus. Zeile im Block hinzufügen Panel wird nicht angezeigt.
Die Status-Funkt. klappt, mit der bereits gemeldeten Einschränkung im Firefox (Slice wird nicht ausgegraut).

Kann jemand das Problem nachvollziehen?

PS: Addon + Plugins habe ich bereits mehrfach neu installiert.

**Comment by alexplusde** [comment]
Reinstalliert oder neu installiert? Auch den Cache gelöscht?

**Comment by iceman-fx** [comment]
Ja, habe ich beides bereits mehrfach gemacht.
Auch die aktuellste Version funzt nicht bei mir.

**Comment by omphteliba** [comment]
@iceman-fx das kann ich bestätigen.

**Comment by schuer** [comment]
Bitte nochmal die aktuelle Version 1.4.0 testen. Ich konnte den beschriebenen Fehler leider nicht nachvollziehen, blÖcks und structure/version funktionierten bei mir zusammen problemlos.

**Comment by omphteliba** [comment]
Geht auch mit bloecks 1.4.0 nicht. Wenn ich das "Cut-n-Paste" Icon anklicke erscheint nicht mal die Meldung dass der Slice kopiert wurde.

**Comment by schuer** [comment]
Danke fürs Testen, @omphteliba. Dann schaue ich mir das nochmal an, sobald wieder Zeit ist.

**Comment by tema-web** [comment]
Kann das Problem bestätigen. Bei mir R5.7.1, bloecks 1.4.0
Kopieren funktioniert in der Live-Version, aber nicht in der Arbeitsversion. Einfügen von aus der Live-Version kopierter Blöcke in die Arbeitsversion geht aber.

**Comment by schuer** [comment]
Danke euch, ich kann es nun nachvollziehen und kümmere mich um einen Fix.
