### ISSUE TITLE
Neues Plugin: Zeitfenster der Veröffentlichung (Status on/off)

### ISSUE THREAD

**Issue by metaphon** [FriendsOfREDAXO/bloecks#48]
Sehr praktisch wäre, wenn man jedem Block auch noch einen **Zeitraum der Veröffentlichung** mitgeben könnte.
Für einige meine Module habe ich schon eine Lösung, die die Zeitangaben (Startdatum, Uhrzeit bis Endedatum, Endeuhrzeit) in einer Redaxo-Modulvariable speichert.

**Comment by elpschulzo** [comment]
Au ja. Das haben meine Kunden auch schon mehrfach angefragt.

**Comment by pschuchmann** [comment]
#74 Ich hab da mal was gebaut, testet das gerne mal gegen. Auf der Blöcks Addon Seite gibt es eine weitere Seite Tme Switch. Dort können Datensätze angelegt werden unter Angabe der Slice ID und eines Start- bzw. Enddatums.

**Comment by alexplusde** [comment]
Sollte das in Zukunft Teil von bloecks/status werden oder wird das dann ein anderes Plugin, jetzt, da status ab R5.10 obsolet ist?

**Comment by metaphon** [comment]
Ich denke als Teil von bloecks ist es gut verortet.
