### ISSUE TITLE
Wird hier noch aktiv entwicklet?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/bloecks#49]
Hallo @tgoellner,

bist du hier noch "am Ball"?

LG
Oliver

**Comment by alexplusde** [comment]
Scheint nicht so. @tgoellner

**Comment by skerbis** [comment]
hmm - schade

**Comment by skerbis** [comment]
Ja, wird gemacht

**Comment by mbodon** [comment]
und gibt es da schon jemand der weiterentwickelt ... das Addon ist ja eigentlich "essentiell" ;-)

**Comment by schuer** [comment]
Im Slack wurde neulich diskutiert, und die Community/FOR muss die Weiterentwicklung sicherlich auffangen, weil Thomas nicht mehr aktiv ist.

Dass hier Pflegebedarf ist, wurde also kommuniziert, und Olivers ursprüngliche Frage beantwortet, deshalb schließe ich mal hier. Bei Bedarf gerne wieder öffnen!
