### ISSUE TITLE
Gut gemeint, gefällt mir bisher nicht.

### ISSUE THREAD

**Issue by erraiva** [FriendsOfREDAXO/bloecks#5]
Hallo Freunde
warum ist denn Slice_UI im Installer nicht mehr verfügbar?
Slice_UI funktioniert tadellos und bietet die Dinge, die ich unverzichtbar finde. Jetzt muss ich das Addon manuell installieren. Schade. Solange bloecks noch nicht vollständig funktioniert ...

Viele Grüße
Heinz

**Comment by skerbis** [comment]
Ganz einfach, weil es nicht weiterentwickelt wird und der ursprüngliche Programmierer nichts mehr für Redaxo macht. Zudem waren dort einige Baustellen, die sehr buggy waren. Spiel besser nicht zu oft mit dem Drag & Drop bei den slices, kann gefährlich werden.
