### ISSUE TITLE
Ausgeblendeter Block wird bei Redakteuren nicht transparent 

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/bloecks#55]
Wenn man nicht Admin ist, sondern Redakteur, wird der ausgeblendete Block nicht transparent angezeigt. 

Reproduzieren: Block ausblenden und Identität wechseln zu einem Benutzer mit Nicht-Admin-Rechten

**Comment by mbodon** [comment]
+1 
Erst wenn man die "blÖcks Einstellungen" erlaubt funktioniert es als Redakteur - allerdings erscheint dann im Menü unter AddOns dann blÖcks was unschön ist und auch keine Funktionalität bietet (Keine Plugin-Einstellungen verfügbar. Zur AddOn-Seite wechseln). Ich bitte darum wenigstens nicht den Eintrag unter AddOns im Menü zu erstellen.

**Comment by alexplusde** [comment]
duplicate #42
