### ISSUE TITLE
Fehler unter Redaxo 5.7

### ISSUE THREAD

**Issue by engel4u** [FriendsOfREDAXO/bloecks#59]
In Redaxo 5.7 wird bei den Artikeln das Icon für "anzeigen" bzw. "verstecken" nicht mehr angezeigt. Der Link ist aber (im Quellcode), man sieht halt nur nichts.

**Comment by staabm** [comment]
kannst du einen screenshot liefern von welchem icon du sprichst und wo es fehlt?

**Comment by engel4u** [comment]
Unter Redaxo 5.6.5 wird das Icon angezeigt. Unter Redaxo 5.7 ist der Link vorhanden, aber man sieht kein Icon. 
Der Quellcode lautet jeweils: 
`<div class="btn-group btn-group-xs"><a href="/redaxo/index.php?page=content/edit&amp;article_id=1&amp;bloecks=status&amp;module_id=1&amp;slice_id=57&amp;clang=1&amp;ctype=1&amp;status=0" class="btn btn-visible" title="Block offline stellen" data-state="visible"><i class="rex-icon rex-icon-visible"></i><span class="sr-only">Block offline stellen</span></a></div> `

![fehler_bloecks](https://user-images.githubusercontent.com/46758536/55105213-4e605f80-50cc-11e9-8819-ddef3f6d1ce7.png)

**Comment by staabm** [comment]
Wird in https://github.com/redaxo/redaxo/issues/2674#issuecomment-477568888 erledigt
