### ISSUE TITLE
Slices verschwinden, wenn ein Slice editiert wird

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#6]

**Comment by tgoellner** [comment]
Bezieht sich auf die alte Version (< 1.1-alpha), das Columns-Plugin muss nochmal komplett überarbeitet werden.

**Comment by skerbis** [comment]
Das besagte PlugIn gibt es wohl nicht mehr und daher auch diesen Fehler nicht. Wenn ich das richtig sehe. Daher erstmal close
