### ISSUE TITLE
"Ein Fehler trat auf (beim Verschieben nach oben)."

### ISSUE THREAD

**Issue by elpschulzo** [FriendsOfREDAXO/bloecks#66]
Hab hier nen Artikel, in dem schon viel passiert (ist). Blöcke angelegt, Blöcke gelöscht, etc. Wenn ich per D&D verschiebe, kommt fast immer "Ein Fehler trat auf (beim Verschieben nach oben).".

Ich muss dann mit den Pfeilen verschieben, was nervig ist. Kann man das irgendwie sinnvoll und schnell debuggen? @schuer

**Comment by schuer** [comment]
@elpschulzo Hast du zufällig das FOR-AddOn SEO-Inspector installiert? Das macht komische Sachen im Zusammenspiel mit bloecks.

**Comment by schuer** [comment]
Mit Version 1.4.1 wurde einiges diesbezüglich gefixt, @elpschulzo.

Ich hoffe, dass sich dein Thema damit auch erledigt hat und würde mal provisorisch hier schließen. Sollte es nochmal aufkommen, mach gerne wieder auf und liefer mir dann möglichst Daten oder einen Zugang, mit denen ich das Problem nachvollziehen kann.
