### ISSUE TITLE
Akkordeons in Blockausgabe - (Backendansicht) erhalten Greifer von Blöcks 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/bloecks#71]
![Bildschirmfoto 2019-07-14 um 18 26 28](https://user-images.githubusercontent.com/791247/61186389-f93d5f00-a664-11e9-9217-2b4d9bd4a916.png)

**Comment by schuer** [comment]
@skerbis Was für Accordions sind das? In der Modulsammlung finde ich nichts. Hast du weitere Infos oder kannst mir zumindest die HTML-Struktur hier reinkopieren?

**Comment by skerbis** [comment]
Das sind klassische bootstrap Akkordeons .. Code folgt

**Comment by schuer** [comment]
Screenshot aus Developer Tools würde auch reichen. Ich würde nur gerne sehen, welche Styles vererbt werden, um den Bugfix dann auch testen zu können.

**Comment by skerbis** [comment]
Ausgangscode:

```php
 <div class="panel panel-default">
            <div class="panel-heading">
              <a data-toggle="collapse" data-parent="#accordion3030" href="#collapse2">Spielverlegungen / Spielansetzungen</a>
            </div>
            <div id="collapse2" class="panel-collapse collapse">
                <div class="panel-body">

```

Ergebnis

![Bildschirmfoto 2019-07-15 um 08 38 18](https://user-images.githubusercontent.com/791247/61198972-75bf5480-a6dc-11e9-9ab2-7ce28af66317.png)

**Comment by schuer** [comment]
Danke, gefixt!
