### ISSUE TITLE
Erweiterungs-Wunsch: Stapel-Kopieren / -Verschieben

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/bloecks#72]
Ich habe bei vielen mehrspaltigen Homepages die Situation, dass ein thematischer Block über mehrere Spalten geht und diverse Inhalte hält, die dann (als Gesamtblock) auf mehreren Seiten, ggf. leicht abgewandelt, untergebracht werden sollen.

Wenn man mit bloecks kopiert, geht das immer nur für 1 Slice. Man muss dann sehr viel klicken, um alle einzelnen Blöcke in x Artikel einzufügen. Noch "ätzender" als das Geklicke ist aber das Wieder-Zusammenpuzzeln in der richtigen Reihenfolge an der richtigen Stelle.

**Idee 1:** 
Neben dem Greifer zum DnD-Verschieben Checkboxen implementieren. Wenn mind. 1 geklickt ist, werden nicht-selektierte ausgegraut oder sonst wie als "nicht aktiv" gekennzeichnet. Man kann dann mehrere Checkboxen klicken und so einen Stapel als Slices zusammenstellen. Die Kopieren und Ausschneiden Buttons sollten dann eine Zahl vor dem Icon bekommen, die immer der Anzahl der selektierten Blöcke im Stapel entspricht, damit besser visualisiert wird, dass man eben x Blöcke kopiert/ausschneidet und nicht nur den einen, dessen Buttons man dazu benutzt.

_Vorteile:_

- Man kann frei Blöcke zusammenfassen, die nicht benachbart sind

_Nachteile_

- evtl. intuitiv schwer zu verstehen (wofür ist die Checkbox da? (evtl. mit guten Tooltips unterstützen))
- evtl. verwirrend, wenn man die Copy-Buttons eines spezifischen Blocks nutzt, um alle selektierten zu kopieren --> ggf. spezielle absolut positionierte Controls zusätzlich einführen

**Idee 2:**
Analog Photoshop und anderen Programmen kann man benachbarte Slices _verknüpfen_. Das Ketten-Icon ist sehr gebräuchlich dafür und sollte intuitiv gut zu verstehen sein. 2 benachbarte, verknüpfte Slices sind dann visuell durch einen gemeinsamen Rahmen, eine Verbindungs-Linie zwischen den Blöcken u.ä. gut sichtbar verknüpft. Copy/Cut/Move/DnD-Move Buttons werden bei allen verknüpften Slices ausgeblendet, außer beim ersten.
Bei Mouseover über einen Block erscheinen dann 2 Buttons, z.B. so:

![bloecks_link_button](https://user-images.githubusercontent.com/7023022/61702386-fd8e0a00-ad3f-11e9-8fef-629be20888a5.png)

Der Rückweg wäre dann ein "Verknüpfung aufheben" o.ä. wobei dann auch alle nachfolgenden Verknüpfungen gelöst werden müssten (falls man z.B. eine 5er Verknüpfung an 3. Stelle löst)

_Vorteile:_

- nutzbar auch für DnD-Move um Stapel zu verschieben
- intuitiv gut greifbar
- Verknüpfungen sollten persistent in einer DB-Table gespeichert werden. Daraus ergeben sich weitere Vorteile:
-- man könnte eine API anbinden, die mit z.B. `rex_slice_group::get(182)->print()` die Inhalte eines Slice-Stapels irgendwo ausgibt (kann sinnvoll sein, wenn man oft oder auf jeder Seite einen festen Block haben will, der von Redakteuren aber editierbar sein soll) (weitere Funktionen der API würden sich dann bestimmt ergeben)
- passt zum AddOn-Namen "bloecks" :)>

_Nachteile:_

- evtl. zu groß/aufwändig --> eigenständiges AddOn mit bloecks als Requirement?
- Umgang mit Mehrsprachigkeit / Versionen etc. noch unklar

----------------------

Die Umsetzung des Block-Verknüpfens wäre eine sehr feine Sache, da man das, wie schon durch den API-Ansatz beschrieben, auch anderweitig sicher clever einsetzen könnte. Noch weiter gesponnen kann man in der Bloecks-Config Surrounding-Tags angeben für Block-Gruppen und so z.B. im Frontend auch schneller Layouts generieren (bspw. Cards).

Was haltet ihr davon?

**Comment by schuer** [comment]
Das ist mal ausführlich beschrieben, chapeau @elpschulzo!

Ich finde Idee 2 prima, bei der man Blöcke verknüpfen kann. Das könnte Blöcks auf den ersten Blick sehr gut mittels Plugin lösen, und die anderen Plugins Status, DND, CP könnten einen verknüpften Zustand entsprechend respektieren.

Mir fehlt leider komplett die Zeit, ich wollte aber zumindest kurz anmerken, wie gut ich die Idee finde! :)

**Comment by VIEWSION** [comment]
... ja - genau dazu wollte ich auch ein enhancement issue schreiben.... wäre echt klasse

**Comment by iceman-fx** [comment]
Ich hänge mich hier auf mal mit dran.
Auch ich fände ein Funktion zum Kopieren/Ausschneiden mehrerer oder aller Slices eines Artikels toll, da auch ich es öfters habe, dass man wild hin und her klickt, um die Inhalte weitgehend zu übernehmen ohne den gesamten Artikel duplizieren zu müssen.
