### ISSUE TITLE
Drag & Drop für mobile Geräte automatisch deaktivieren

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/bloecks#75]
Hallo,
ich teste gerade die Funktionen auf einem Android tablet. 
Leider kann ich bei aktivem Drag & Drop auf dem Tablet nicht mehr die Blöcke zueinander verschieben. 

Die Anfasser greifen bei Touch nicht und die sonst bekannten Pfeile sind ja leider auch nicht da. 

Es wäre schön, wenn man auf mobilen Geräten wieder die Pfeile hätte, um Verschiebungen vornehmen zu können. 
Natürlich wären auch funktionierende Anfasser toll.

Getestet unter Rex5. 8 mit allen aktueller Bloecks-Version

**Comment by schuer** [comment]
> Es wäre schön, wenn man auf mobilen Geräten wieder die Pfeile hätte, um Verschiebungen vornehmen zu können.

@iceman-fx Diese Option kannst du auf der blÖcks-AddOn-Seite einstellen, indem du die Checkbox anhakelst bei »Zeige Sortierungs-Buttons an den einzelnen Modulblöcken.«

**Comment by iceman-fx** [comment]
Mhhh.
nur wo finde ich diese Einstellungsseite???

Wenn ich das Addon anklicke kommt nur:
blÖcks - Modulerweiterungen
Keine Plugin-Einstellungen verfügbar. Zur AddOn-Seite wechseln.

Selbst in der 2.0er Version habe ich keine Einstellungen, nur die Hilfen.

**Comment by schuer** [comment]
Sieht das bei dir nicht so aus? Bist du als Admin angemeldet? Wenn nicht, hast du die entsprechenden Benutzerrechte vergeben?

![Screenshot 2019-09-20 at 17 08 59](https://user-images.githubusercontent.com/1297466/65337922-66bbbd80-dbc9-11e9-9624-3cb5dbd36d91.png)

**Comment by iceman-fx** [comment]
Nachdem ich es jetzt nochmal neu installiert habe, habe ich auch diese checkbox.
Danke.
