### ISSUE TITLE
Offline Badge - korrekte Darstellung

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#78]
Soll das so erscheinen?

<img width="1021" alt="Bildschirmfoto 2019-09-26 um 12 16 33" src="https://user-images.githubusercontent.com/338267/65680622-a108dd00-e057-11e9-8919-ab73fea88336.png">

**Comment by schuer** [comment]
Nein. Wurde das CSS wieder nicht aktualisiert? Kannst du mal BlÖcks und die Plugins reinstallieren, damit die Assets aktualisiert werden. Und ggfls. Browsercache löschen.

**Comment by tbaddade** [comment]
Hat sich erledigt. Das CSS kam direkt aus einem Modul.
