### ISSUE TITLE
CSS Maps werden nicht gefunden 404

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#79]
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) 
https://project.localhost/redaxo/plugins/status/assets/css/be.css.map

[Error] Failed to load resource: the server responded with a status of 404 (Not Found) 
https://project.localhost/redaxo/assets/css/be.css.map
```

**Comment by schuer** [comment]
Die Sourcen landen nicht mit im Release, deshalb sind Sourcemaps dort eigentlich unnötig. Aber der Grunt-Workflow des Projekts unterscheidet nicht zwischen DEV und PROD, es wird einfach immer minifiziert und Sourcemaps ausgegeben. Wenn man lokal mit der Git-Version arbeitet, funktioniert es, aber als Release ausgeliefert dann nicht mehr.

Wie wollen wir mit dem Thema umgehen?
a) Sourcen mit ins Release stecken, so dass sie auch in PROD funktionieren.
b) Den Grunt-Workflow anpassen, so dass zwischen DEV und PROD unterschieden wird und Sourcemaps in PROD nicht mehr verwendet werden. (Darauf hätte ich wenig Zeit und Lust.)
c) Sourcemaps komplett entfernen.
d) Alles so lassen, wie es ist.

Ich wäre für a) oder d), und ihr?

**Comment by tbaddade** [comment]
Ich wäre für **b)** sofern jemand das anpassen mag, ansonsten für **a)**, sodass zumindest die 404 verschwinden (Pfade müssten aber angepasst werden)

Wäre es ne Option das Bimmelbam (wenn es Prod und dev unterscheidet) oder Yimmelyam Setup hier zu übernehmen?

**Comment by schuer** [comment]
@tbaddade Variante b) war nun doch einfach umzusetzen.

**Comment by tbaddade** [comment]
Merci 🌟

**Comment by tbaddade** [comment]
Kann das mit Version 2.1.1 wieder verloren gegangen sein? Lokal bekomme ich wieder den obigen Fehler.

**Comment by schuer** [comment]
@tbaddade Ja, das letzte Release scheint nicht als `--production` gebaut worden zu sein, deshalb sind die Assets unminifiziert, und es sind Sourcemaps dabei.
Danke für den Hinweis!

**Comment by tbaddade** [comment]
Sollte man ggf. auf den Grunt Workflow verzichten?

**Comment by schuer** [comment]
Der Grunt-Workflow ist zwar inzwischen furchtbar alt, aber wurde sehr durchdacht angelegt (rsync kopiert kompilierte Assets direkt rüber, so dass sie REDAXO ohne re-install des AddOns zur Verfügung stehen, sehr praktisch!) und funktioniert eigentlich nachwievor gut.
Ich selbst hätte wenig Lust, den Workflow grundlegend anzupassen.

Allerdings habe ich beim letzten Release offenbar nicht richtig aufgepasst. Werde mir nochmal in Ruhe anschauen und ein sauberes Release nachlegen.

**Comment by tbaddade** [comment]
Danke dir … wegen des Kopierens … Sobald man eine neue Version via Installer hochladen mag, kann man eine Checkbox "Assets aus dem Root-Assets-Ordner nehmen" anhakeln. Man muss aber dennoch aufpassen, da bei einem re-install die Änderungen wieder verloren gehen. Das nur als Info, nutze ich aber selbst nicht.

**Comment by schuer** [comment]
@tbaddade Habe es mir angeschaut, Version 2.1.1 ist sauber. Sollte eigentlich kein Sourcemaps-Problem haben. Ich hatte das lediglich in 2.1.0 verbaselt. Vielleicht schaust du nochmal in deiner Installation nach, woran es liegen könnte?

Und ja, ein allgemeiner Prozess für Assets wäre schon recht sinnvoll, damit nicht alle ihr eigenes Süppchen kochen (bzw kaum jemand kocht ja überhaupt bisher).

**Comment by tbaddade** [comment]
Ich schließe, da ich es nicht mehr nachstellen kann.

Einen allgemeinen Prozess sollten wir vielleicht dann hier weiter diskutieren
https://github.com/FriendsOfREDAXO/friendsofredaxo.github.io/issues
