### ISSUE TITLE
UI: Button überlagert das Auswahlmenü bei Hover

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/bloecks#80]
Beim der Auswahl eines Moduls aus dem Dropdown-Menü wird der darunter liegende »Block hinzufügen«-Button beim Hover aktiv wird und überlagert das Menü.

<img width="938" alt="block_hinzufuegen_3" src="https://user-images.githubusercontent.com/1297466/65690089-9c9bee80-e06e-11e9-9380-5ab10aa24288.png">

**Comment by madiko** [comment]
Dirk, Danke! Wollte ich schon ewig schreiben, doch besser spät als nie ;-)

**Comment by schuer** [comment]
Gerne :)
