### ISSUE TITLE
Cache wird nach Offline-Schalten eines Blocks nicht korrekt neu generiert.

### ISSUE THREAD

**Issue by netzproductions** [FriendsOfREDAXO/bloecks#81]
In einem Multi-Domain-System (Redaxo v5.8.0, bloecks v2.0.1) wird der Artikel-Cache nicht korrekt zurückgesetzt, wenn Blöcke online oder offline geschaltet werden.

Konkrete Situation: ein Block ist offline geschaltet und nicht im Frontend sichtbar. Nun wird der Block sichtbar geschaltet, und danach wieder offline geschaltet, ist aber weiterhin im Frontend sichtbar. Erst wenn der Gesamtcache manuell geleert wird, stimmt die Sichtbarkeit wieder.

Nach Kontrolle der entsprechenden .content-Datei hat diese den deaktivierten Block enthalten, was nicht sein dürfte.

Ähnliche Probleme gab es in der Vergangenheit beim Einsatz des Plugins seoinspector, dieses läuft hier jedoch nicht.

**Comment by schuer** [comment]
Ich kann den Fehler hier leider nicht nachstellen. YRewrite 2.6 ist aktiv, R 5.8 und Blöcks 2.0.1 wie bei dir, aber der Flow funktioniert fehlerfrei: Offline-Block online setzen und direkt wieder offline.

**Comment by netzproductions** [comment]
Ich konnte es nun isolieren: Auslöser ist ein Plugin, welches ich zur Aufnahme von OpenGraph-Infos im Artikel geschrieben habe, und was eine Form in der Seitenleiste einklinkt.
Sobald ich die Zeilen
`$articleContentInstance = new rex_article_content($article_id, $clang);
$articleContent = $articleContentInstance->getArticle();`
rausgenommen hatte, war der Fehler behoben.

**Comment by schuer** [comment]
Danke fürs Nachforschen! Kurz zur Erklärung: BlÖcks’ Status funktioniert nicht, wenn ein Artikelinhalt im Backend generiert wird. Denn es unterscheidet zwischen Frontend und Backend in der Form, dass im Frontend der Status greift, im Backend jedoch nicht. Denn im Backend will man ja alle Artikel sehen, egal ob online oder offline.

Wenn in eigenen AddOns also der Artikelinhalt generiert wird, sollte vorher immer in den Frontend-Modus (und danach zurück in Backend) gewechselt werden: `rex::setProperty('redaxo', false)`
Siehe das Beispiel Cache-Warmup: https://github.com/FriendsOfREDAXO/cache_warmup/blob/5f1b9cb8fbfeca8c1849a7b65483f62bfb62295d/boot.php#L55-L61
