### ISSUE TITLE
Offline Slices im Frontend anzeigen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#82]
Eventuell oben rechts neben der Quicknavi ein Toogle anbringen.

Wenn das Toggle aktiv, kann der im Backend eingeloggte Admin auch die offline Slices im Frontend sehen.

**Comment by alexplusde** [comment]
Ist das nicht eher ein Feature, das mit "Arbeitsversion" abgedeckt ist?

**Comment by tbaddade** [comment]
> Ist das nicht eher ein Feature, das mit "Arbeitsversion" abgedeckt ist?

Ich sehe es eher als das an, was ich auch mit offline Artikel anstelle. Ich lasse die nur für eingeloggte User anzeigen. Andere bekommen die 404 Seite.

**Comment by dpf-dd** [comment]
Zusammengefasst ein spontanes Feedback zweier meiner Redakteure die ich nebenbei mal befragt habe:
"Warum sollte ich Offline-Blöcke im Frontend sehen wollen? Reicht doch im Backend?"
"Muss ich mich dann jedesmall erst ausloggen wenn ich eine Frontend-Useransicht gegenprüfen möchte?"

Anmerkung: Das Redaxo der befragten Redakteure arbeitet mit installiertem version-Addon, die sind also den Workflow mit Live- & Arbeitsversion gewohnt.

Just my 2 cents :)

**Comment by schuer** [comment]
Ich persönlich fände das Feature nicht wichtig genug, um dafür eine Option im UI vorzusehen — Zumindest nicht im aktuellen Backend.

Inhaltlich stimme ich @tbaddade zu, dass der Platz oben rechts neben der Quicknavi am geeignetsten wäre.

**Comment by alexplusde** [comment]
Ich mache hier mal zu, da es bloecks/status nicht mehr geben wird, sondern im Core zu Hause ist.

**Comment by tbaddade** [comment]
> Ich mache hier mal zu, da es bloecks/status nicht mehr geben wird, sondern im Core zu Hause ist

Wäre es nicht innvoller die Issues zu transferieren anstatt diese jetzt hier einfach zu schließen. Die Themen sind ja immer noch vorhanden.

**Comment by alexplusde** [comment]
Klar, fühl dich frei. Ich war mir unsicher, ob ich das direkt machen soll.

**Comment by alexplusde** [comment]
...

**Comment by tbaddade** [comment]
> ...

Verstehe nicht was das du sagen willst

**Comment by tbaddade** [comment]
Hier kann man weiter diskutieren https://github.com/redaxo/redaxo/issues/3407
