### ISSUE TITLE
Modultitel

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/bloecks#83]
Hey,

mir ist eben aufgefallen, dass es das CSS ein wenig zerhaut, wenn man einen Offline Block editiert:

![image](https://user-images.githubusercontent.com/35096518/69547431-df5a4400-0f95-11ea-81a5-269104e5ded7.png)

Es fehlt die Klasse `rex-slice-status-off`, damit das CSS greift. Ergänzt man die Klasse wird dann allerdings auch der Panel Body ausgegraut.

**Comment by schuer** [comment]
@pschuchmann Kann ich bestätigen. Danke fürs Melden!
