### ISSUE TITLE
Offline Slices werden scheinbar via E-Mail mitgesendet

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#84]
Ich notiere das Issue mal hier.

Aktuell versenden wir bei einem Projekt via PHPMailer REDAXO-Artikel die dann als HTML angezeigt werden.
Die Offline Slices werden von Blöcks scheinbar aktuell nicht gefiltert.

**Comment by schuer** [comment]
@tbaddade Wenn du im Backend-Modus bist, werden grundsätzlich alle Slices ausgegeben. Blöcks blendet Slices nur im Frontend aus. Das wird vermutlich euer Problem hier sein?

**Comment by dpf-dd** [comment]
@tbaddade Das erinnert mich an den Thread hier:
https://github.com/TobiasKrais/multinewsletter/issues/39

Vielleicht ist da schon eine Lösung dabei?

**Comment by tbaddade** [comment]
Danke für die Hinweise, muss jedes AddOn für sich wohl klären.
