### ISSUE TITLE
Offline-Status defekt, wenn Artikelinhalt bereits vorm EP SLICE_SHOW generiert wird

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/bloecks#86]
## Problembeschreibung:

Wenn du im Backend [`rex_article_content->getArticle()`](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php#L262) verwendest, wird dir REDAXO alle Slices liefern, auch die Offline-Slices. Schlimmer noch: Es werden dabei bereits die [Cache-Files für den Artikel generiert](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/structure/plugins/content/lib/article_content.php#L94), die dann ebenso die Offline-Slices abbilden und sie damit sogar im Frontend ausbringen. Du hebelst damit also den blÖcks-Mechanismus vollständig aus. **Denn blÖcks greift erst/nur beim EP [SLICE_SHOW](https://github.com/redaxo/redaxo/blob/master/redaxo/src/addons/structure/plugins/content/lib/article_content_base.php#L342) ein.**

### Code-Beispiel, das den Fehler zeigt:

Innerhalb der `boot.php` des Project-AddOns:

```php
<?php
$article = new rex_article_content(42);
$content = $article->getArticle();
```

## Fix?

Ich habe jetzt nicht alles bis ins Detail zerpflückt, aber mir scheint, es gibt auf Seite von blÖcks gar keine andere Lösung dafür. Wollte man ermöglichen, dass sowas wie `rex_article_content->getArticle()` richtig mit Offline-Slices umgeht, müsste man es im Core bzw. im Structure-AddOn implementieren, nicht in blÖcks.

Vielleicht hat jemand eine Idee?

**Comment by tbaddade** [comment]
> Wollte man ermöglichen, dass sowas wie `rex_article_content->getArticle()` richtig mit Offline-Slices umgeht, müsste man es im Core bzw. im Structure-AddOn implementieren, nicht in blÖcks.

Sehe ich auch so. Ich würde sogar soweit gehen, dass man auch für andere Tabellen gleich das Feld `status` mit aufnimmt. Für Module, Templates, Medien, Medienkategorien, Metainfo etc. Die Tabellen sozusagen insgesamt ein wenig mehr angleichen.

**Comment by alexplusde** [comment]
Ich mache hier mal zu, da es bloecks/status nicht mehr geben wird, sondern im Core zu Hause ist.

**Comment by tbaddade** [comment]
Kann geschlossen bleiben, da der Core die Slices nicht in den Cache schreibt.
