### ISSUE TITLE
Zwei Slices gruppieren, aber wie?

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#9]
Wie gruppiert man 2 Slices, also das diese Slices eben speziellen CSS-Klasesn bekommen?

Modul Id funktioniert nicht, da dieses dann auf alle Module fällt. 
Bsp.: Ein Slice mit dem Modul "YForm - Formbuilder" soll neben einem anderen Slice stehen.

**Comment by tgoellner** [comment]
Bezieht sich auf die alte Version (< 1.1-alpha), das Columns-Plugin muss nochmal komplett überarbeitet werden.

**Comment by skerbis** [comment]
Columns-Plugin gibt es nicht mehr - close
