### ISSUE TITLE
Im Changelog ist nur die primäre Sprache vorhanden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/bloecks#90]

**Comment by schuer** [comment]
Hey @tbaddade, kannst du das näher erläutern? Das Changelog liegt nur in einer Datei vor, in diesem Fall bereits auf Englisch, und es ist doch eher unüblich, Changelogs für jede Sprache zu pflegen?

**Comment by tbaddade** [comment]
Ich finde es nicht schick, wenn man im Installer bei Updates ständig zwei Sprachen sieht.

**Comment by gharlan** [comment]
@tbaddade Wir sitzen hier und rätseln, was du genau meinst. Stört dich, dass die meisten Addons das Changelog in deutsch schreiben, und bloecks aber in englisch?
Also wärest du dafür, dass bloecks das Changelog auch auf deutsch statt englisch schreiben soll?

Ich finde es ok, wenn es englisch ist. Eigentlich finde ich, wir sollten die allgemein auf englisch schreiben.

**Comment by tbaddade** [comment]
Braucht nicht weiter rätseln ... Coded lieber :)
