### ISSUE TITLE
Bloecks für R 5.10 anpassen

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/bloecks#94]
REDAXO 5.10 wird den Slice-Status im Core abhandeln, so dass das Blöcks-Plugin nicht mehr notwendig ist, siehe https://github.com/redaxo/redaxo/pull/3369

Folgende Anpassungen müssten vorgenommen werden:

1. bloecks/status darf beim Deinstallieren nicht mehr das `status`-Feld in der DB entfernen.
2. bloecks/status darf bei Verwendung mit REX >= 5.10 keine Funktion mehr anbieten. Für ältere REDAXO-Versionen bleibt sie wie bisher erhalten.
3. Bloecks sollte die Nutzer bei Verwendung mit REX >=5.10 darauf hinweisen, dass bloecks/status entfernt werden kann, weil REDAXO die Aufgabe inzwischen selbst übernimmt.
4. READMEs und Changelog entsprechend anpassen
5. Neues Major-Release 3.0.0 veröffentlichen

**Comment by alexplusde** [comment]
ich würde das wie gesagt in 2 Versionen packen
Die Version für 5.9 deinstalliert nicht mehr die Felder
Die Version ab 5.10 bietet nur noch die Info

**Comment by schuer** [comment]
Zu aufwendig, @alexplusde. Können wir alles in einer Version abhandeln.

**Comment by alexplusde** [comment]
OK, du machst den Slack-Support dazu, wenn alle jammern, dass ihr Status verschwunden ist, weil ein sicheres Vorgehen zu aufwendig war. :)
