### ISSUE TITLE
.map fehlt cut & copy

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/bloecks#96]
<img width="746" alt="Bildschirmfoto 2020-03-04 um 10 15 42" src="https://user-images.githubusercontent.com/791247/75863702-324b5f00-5e01-11ea-8bf3-7013bb1314ba.png">

**Comment by schuer** [comment]
Interessant, die JS-Sourcen für Cut & Copy fehlen komplett, das ist nie aufgefallen. Es gibt nur das fertig kompilierte JS (mit Sourcemaps), das seit 3 Jahren nicht angefasst worden ist. Und weil die Sourcen fehlen, wurde in all der Zeit nie neues generiert.

Danke für den Hinweis! :)

**Comment by skerbis** [comment]
Mir auch nicht. Aber jetzt beim Betatest 5.10. schaue ich mal genauer hin
